
monolith_module.slider.admin:
    path: /
    defaults:
        _controller: SliderModuleBundle:AdminSlider:index

monolith_module.slider.admin_slider:
    path: /{id}/
    defaults:
        _controller: SliderModuleBundle:AdminSlider:slider
    requirements:
        id: \d+

monolith_module.slider.admin_slider_item_edit:
    path: /item/{id}/
    defaults:
        _controller: SliderModuleBundle:AdminSlider:slideEdit
    requirements:
        id: \d+

monolith_module.slider.admin_slider_edit:
    path: /{id}/edit
    defaults:
        _controller: SliderModuleBundle:AdminSlider:sliderEdit
    requirements:
        id: \d+
